export const BAD_GATEWAY_STATUS_CODE = 502;
export const BAD_REQUEST_STATUS_CODE = 400;
export const FORBIDDEN_STATUS_CODE = 403;
export const MAINTENANCE_CODE = 503;
export const NOT_FOUND_CODE = 404;
export const TOO_MANY_REQUESTS_STATUS_CODE = 429;
export const UNAUTHORIZED_STATUS_CODE = 401;
export const UNPROCESSABLE_STATUS_CODE = 422;